version: '3'

services:
  postgres:
    restart: always
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - djangonetwork
    ports:
      - '5433:5432'
    env_file:
      # 環境変数に設定するファイル
      - ./postgres/.env.db
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

  web:
    build:
      context: ./todowoo-project/
      dockerfile: Dockerfile
    # サービス起動後に入力されるコマンドを設定
    command:
        python manage.py runserver 0.0.0.0:8000
    # データを永続化させる場合の設定。`host:container`でパスを記載
    volumes:
      - ./todowoo-project:/usr/src/app/
    # 開放するポートを指定。`host:container`でポートを記載
    ports:
      - '8000:8000'
    # 環境変数を指定
    env_file:
      - ./todowoo-project/.env
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - djangonetwork


# トップレベルに書く「名前付きvolumes」は複数サービスから参照できる
volumes:
    postgres_data:


networks:
    djangonetwork:
      driver: bridge
